### ISSUE TITLE
oAuth 표준에 어긋납니다

### ISSUE THREAD

**Issue by juyoungyoo** [Jaeyeonling/spring-boot-oauth2#1]
https://github.com/Jaeyeonling/spring-boot-boilerplate/blob/d2e54a942004b04180b7a6e694fc02c686e48913/src/main/java/com/jaeyeonling/oauth2/security/social/SocialLoginRequest.java#L13

**Comment by jaeyeonling** [comment]
https://github.com/Jaeyeonling/spring-boot-boilerplate/pull/2

해당 수정내용 확인 부탁드립니다!
